### ISSUE TITLE
Need this module supporting whmcs V8.1.3

### ISSUE THREAD

**Issue by udoyhasan** [sslcommerz/SSLCommerz-WHMCS#2]
Need this module supporting whmcs V8.1.3

**Comment by udoyhasan** [comment]
I edited 1 line and it is working perfectly on our site :)

**Comment by raisulmushfeq** [comment]
Hi @udoyhasan ,
May we know what did you change?
Thanks

**Comment by udoyhasan** [comment]
I did it a long time ago. I currently don't have that edited module with me. I need to recheck this module to make changes. And currently because of my upcoming exam I'll not be able to review this module.
